### ISSUE TITLE
Add and remove tree items after creation

### ISSUE THREAD

**Issue by micage** [longmatthewh/jquery-a11ytree#10]
Hi Matt,

Is there a way to add new tree items after the a11ytree has been initialized?
By now I'm creating the a11ytree by traversing my own tree class (which has no UI).
While traversing it generates a UL/LI-hierarchy, which is then passed to the a11ytree constructor.
I empty and rebuild the a11ytree from scratch every time I modify my own tree. This looses also all aria attributes (selected, expanded). I suppose there might be a better way to solve this. 

What I have in mind is: 
```
Plugin.prototype.addChild($tree, labelText) { ... }
Plugin.prototype.removeChild($tree, labelText) { ... }
// or 
Plugin.prototype.remove($tree) { ... } // removes itself ;)
```
Since you know your tree the best, your help would be very welcome.

**Comment by micage** [comment]
Ok, my last post had a problem: `$("#myUL").a11yTree()` only returns a jQuery object.
But the solution is in your jQuery register code:

```
let myUL = $("#myUL").a11yTree(options);
let a11yTree = myUL.data("plugin_a11yTree");
```
Now it's possible to call the plugins prototype functions e.g.
`a11yTree.collapse($selectedItem);`

I think the rest I will figure out ... somehow.

**Comment by longmatthewh** [comment]
FYI...I have seen issues in the past with trees and screen readers when
additional items are added after initialization, where these items aren't
considered part of the tree.

On Dec 7, 2016 7:25 AM, "micage" <notifications@github.com> wrote:

Ok, my last post had a problem: $("#myUL").a11yTree() only returns a jQuery
object.
But the solution is in your jQuery register code:

let myUL = $("#myUL").a11yTree(options);
let a11yTree = myUL.data("plugin_a11yTree");

Now it's possible to call the plugins prototype functions e.g.
a11yTree.collapse($selectedItem);

I think the rest I will figure out ... somehow.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/longmatthewh/jquery-a11ytree/issues/10#issuecomment-265434568>,
or mute the thread
